"use client";

import { useState } from "react";
import { Loader2, MapPin } from "lucide-react";

import { Button } from "@/components/ui/button";
import { planTrip } from "@/lib/api-client";
import type { PlanTripResponse } from "@/lib/types";

export default function TripDetailsPage() {
  const [source, setSource] = useState("");
  const [destination, setDestination] = useState("");
  const [days, setDays] = useState(3);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");
  const [plan, setPlan] = useState<PlanTripResponse | null>(null);

  const onGenerate = async () => {
    if (!source.trim() || !destination.trim()) {
      setError("Enter origin and destination.");
      return;
    }
    setLoading(true);
    setError("");
    setPlan(null);
    try {
      const data = await planTrip({
        source,
        destination,
        days,
        preferences: { budget: "medium", interests: [], transport: "car" }
      });
      setPlan(data);
    } catch (e) {
      setError(e instanceof Error ? e.message : "Could not generate plan.");
    } finally {
      setLoading(false);
    }
  };

  return (
    <section className="space-y-6">
      <header>
        <h1 className="text-2xl font-semibold tracking-tight">Trip plan</h1>
        <p className="text-sm text-slate-400">Itinerary is generated by Gemini from your inputs—no sample timeline.</p>
      </header>

      <div className="rounded-xl border border-white/10 bg-white/[0.03] p-5">
        <div className="grid gap-3 sm:grid-cols-3">
          <div className="sm:col-span-1">
            <label className="mb-1 block text-xs text-slate-500">From</label>
            <input
              value={source}
              onChange={(e) => setSource(e.target.value)}
              className="w-full rounded-lg border border-white/10 bg-black/25 px-3 py-2 text-sm outline-none"
              placeholder="Origin city"
            />
          </div>
          <div className="sm:col-span-1">
            <label className="mb-1 block text-xs text-slate-500">To</label>
            <input
              value={destination}
              onChange={(e) => setDestination(e.target.value)}
              className="w-full rounded-lg border border-white/10 bg-black/25 px-3 py-2 text-sm outline-none"
              placeholder="Destination"
            />
          </div>
          <div>
            <label className="mb-1 block text-xs text-slate-500">Days</label>
            <input
              type="number"
              min={1}
              max={14}
              value={days}
              onChange={(e) => setDays(Number(e.target.value) || 1)}
              className="w-full rounded-lg border border-white/10 bg-black/25 px-3 py-2 text-sm outline-none"
            />
          </div>
        </div>
        <Button className="mt-4" type="button" disabled={loading} onClick={() => void onGenerate()}>
          {loading ? (
            <>
              <Loader2 className="mr-2 h-4 w-4 animate-spin" />
              Generating…
            </>
          ) : (
            "Generate with Gemini"
          )}
        </Button>
        {error ? <p className="mt-3 text-sm text-rose-300">{error}</p> : null}
      </div>

      {plan ? (
        <div className="space-y-4">
          <div className="rounded-xl border border-white/10 bg-white/[0.03] p-5">
            <h2 className="text-lg font-semibold text-slate-100">Summary</h2>
            <p className="mt-2 text-sm leading-relaxed text-slate-300">{plan.summary}</p>
            <p className="mt-3 text-sm text-slate-400">
              Estimated budget:{" "}
              <span className="font-medium text-slate-200">
                Rs. {typeof plan.estimated_budget === "number" ? plan.estimated_budget.toLocaleString("en-IN") : "—"}
              </span>
            </p>
          </div>

          <div className="space-y-3">
            {plan.itinerary.map((item) => (
              <article key={item.day} className="rounded-xl border border-white/10 bg-white/[0.03] p-5">
                <h3 className="flex items-center gap-2 text-base font-semibold text-slate-100">
                  <MapPin className="h-4 w-4 text-sky-400" />
                  Day {item.day}: {item.title}
                </h3>
                <ul className="mt-3 list-disc space-y-1 pl-5 text-sm text-slate-300">
                  {item.activities.map((act, i) => (
                    <li key={i}>{act}</li>
                  ))}
                </ul>
                <p className="mt-3 text-sm text-slate-400">
                  Stay: <span className="text-slate-200">{item.stay}</span>
                </p>
              </article>
            ))}
          </div>
        </div>
      ) : null}
    </section>
  );
}
